name: Push to master

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: install dependencies
        run: npm ci
      - name: tslint
        run: npm run tslint
      - name: stylelint
        run: npm run stylelint
      - name: test
        run: npm run test:ci
      - name: visual test
        with:
          repository: Legal-General-Group-Digital/rlespinasse-github-slug-action
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: e4699e49fcf890a3172a02c56ba78d867dbb9fd5 # tag:3.1.0
          path: ./github/actions/rlespinasse-github-slug-action
      - uses: ./github/actions/rlespinasse-github-slug-action
        run: npm run eyes-storybook
        env:
          BRANCH: ${{ env.GITHUB_HEAD_REF_SLUG }}

  release:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: zip
        run: zip -r dist/canopy.zip dist/canopy
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
